baseURL = 'https://blog-production-6bc9.up.railway.app/'
languageCode = 'en-us'
title = "Yohai's Blog"
theme = 'blowfish'

[params]
  colorScheme = "ocean"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  enableSearch = true
  enableCodeCopy = true

  [params.homepage]
    layout = "custom"
    showRecent = false

  [params.article]
    showDate = true
    showReadingTime = true
    showTableOfContents = true
    showRelatedContent = false
    showPagination = true
    showBreadcrumbs = true

  [params.author]
    name = "Yohai"
    headline = "Exploring systems programming, UI frameworks, and everything in between"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = true
    style = "dracula"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "draft"
    target = "content/drafts"

[menu]
  [[menu.main]]
    name = "Posts"
    pageRef = "posts"
    weight = 10
  [[menu.main]]
    name = "Drafts"
    pageRef = "drafts"
    weight = 15
  [[menu.main]]
    name = "Tags"
    pageRef = "tags"
    weight = 20

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

